# Generated by Django 3.2.5 on 2021-10-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210922_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name_category',
        ),
    ]
